/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { getBooth } from "@/lib/booths";
import { BoothStamp } from "@/components/Stamp";
import { PhotoCorners } from "@/components/CustomizeStrip";
import PaperTexture from "@/components/PaperTexture";

// Phase 2 public share page — DESIGN.md "New-surface specs > /s/[slug]"
// item 3 ("Full page layout"). A BeReal/Lapse-style single-artifact result
// page: one large static image, one dominant CTA, no photo-viewer chrome.
// The 1200x630 og:image itself is generated by the sibling
// opengraph-image.tsx route (item 2 of the same spec).
export const dynamic = "force-dynamic";

interface Props {
  params: { slug: string };
}

async function getStrip(slug: string) {
  const supabase = getSupabaseServerClient();
  if (!supabase) return null;

  const { data } = await supabase
    .from("strips")
    .select("booth_id, image_path, serial, caption, date_text")
    .eq("share_slug", slug)
    .eq("is_public", true)
    .maybeSingle();
  if (!data) return null;

  const { data: pub } = supabase.storage
    .from("strips-public")
    .getPublicUrl(data.image_path);

  return { ...data, imageUrl: pub.publicUrl };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const strip = await getStrip(params.slug);
  if (!strip) return { title: "Photobooth Passport" };

  const booth = getBooth(strip.booth_id);
  const title = `Admitted at ${booth.name} — No. ${strip.serial || "—"}`;
  const description = strip.caption
    ? `'${strip.caption}' — stamped and filed at ${booth.name}.`
    : "Four exposures. One strip. Stamped for keeps. Issued by The Grand Tour Company.";

  return {
    title,
    description,
    openGraph: { title, description },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function SharePage({ params }: Props) {
  const strip = await getStrip(params.slug);
  if (!strip) notFound();

  const booth = getBooth(strip.booth_id);
  const tagline = strip.caption
    ? `‘${strip.caption}’`
    : "Four exposures. One strip. Stamped for keeps.";

  return (
    <main className="relative mx-auto flex min-h-dvh w-full max-w-app flex-col bg-cream px-5 pb-10 pt-safe-lg">
      <p className="relative z-10 text-center font-geo text-[10px] tracking-[0.26em] text-faded">
        THE GRAND TOUR COMPANY
      </p>
      <h1 className="relative z-10 mt-1 text-center font-display text-[22px] font-bold uppercase leading-snug tracking-[0.05em] text-ink">
        ADMITTED — {booth.name.toUpperCase()}
      </h1>
      {strip.serial && (
        <p className="relative z-10 mt-1 text-center font-geo text-[11.5px] tracking-[0.12em] text-ink-soft">
          No. {strip.serial}
          {strip.date_text ? ` · DATED ${strip.date_text.toUpperCase()}` : ""}
        </p>
      )}
      <p className="relative z-10 mt-2 text-center font-display text-[15px] italic text-ink-soft">
        {tagline}
      </p>

      <div className="relative z-10 mx-auto mt-7 w-full border border-ink/25 border-l-2 border-l-ink/40 bg-cream-deep/45 px-6 py-6 [border-left-style:dashed]">
        <div className="relative mx-auto w-fit">
          {strip.imageUrl && (
            <img
              src={strip.imageUrl}
              alt={`Photo strip from ${booth.name}`}
              className="block w-auto shadow-strip"
              style={{ height: "min(58dvh, 520px)" }}
            />
          )}
          <PhotoCorners />
        </div>
        <div className="pointer-events-none absolute bottom-2 right-2 w-[92px] rotate-[10deg] opacity-[0.13]">
          <BoothStamp booth={booth} />
        </div>
      </div>

      <div className="relative z-10 mx-auto mt-9 w-full max-w-[330px]">
        <a
          href={`/?booth=${booth.id}&ref=${params.slug}`}
          className="press block w-full border border-navy-deep bg-navy px-6 py-4 text-center font-display text-[15px] font-bold uppercase tracking-[0.18em] text-paper shadow-plate"
        >
          Make your own at {booth.name} →
        </a>
        <p className="mt-3 text-center font-geo text-[10.5px] tracking-[0.22em] text-faded">
          NO SIGN-UP — THE CAMERA OPENS AT ONCE.
        </p>
      </div>

      <div className="relative z-10 mx-auto mt-5">
        <a
          href="/"
          className="font-geo text-[13px] tracking-wider text-ink-soft underline decoration-[1.5px] decoration-faded underline-offset-4"
        >
          SEE EVERY BOOTH →
        </a>
      </div>

      <PaperTexture />
    </main>
  );
}
