import type { Booth, BoothId } from "./types";

export const BOOTHS: Booth[] = [
  {
    id: "standard",
    name: "The Standard",
    locale: "HEAD OFFICE, TORONTO",
    stampLocale: "HEAD OFFICE",
    motto: "HONEST LIGHT",
    tagline: "The company's original apparatus. Honest light, plain dealing.",
    place: "Toronto, Canada",
    prefix: "STD",
    accent: "#1F3A5F",
    paper: "#F9F4E9",
    map: { x: 236, y: 112 },
    prompts: [
      "SIT UP STRAIGHT, PLEASE",
      "NOW — A REAL SMILE",
      "LOOK AT YOUR COMPANION",
      "EYES CLOSED, CHIN UP",
      "A BIG LAUGH, GO",
      "PROFILE, PLEASE",
      "LEAN IN TOGETHER",
      "SERIOUS, LIKE A PASSPORT",
    ],
  },
  {
    id: "midnight",
    name: "Midnight Express",
    locale: "SLEEPER CAR No. 9",
    stampLocale: "SLEEPER CAR No. 9",
    motto: "LAST SERVICE 23:59",
    tagline: "Fitted to the night train. Last service 23:59.",
    place: "Aboard the night train",
    prefix: "MDX",
    accent: "#44406E",
    paper: "#F5F0E4",
    map: { x: 182, y: 92 },
    prompts: [
      "PRETEND YOU'RE BEING FOLLOWED",
      "WHISPER A SECRET",
      "LOOK OUT THE WINDOW",
      "TIP AN IMAGINARY HAT",
      "SLEEPY EYES",
      "TOAST WITH INVISIBLE GLASSES",
      "GAZE AT SOMETHING FAR AWAY",
      "CAUGHT MID-LAUGH",
    ],
  },
  {
    id: "seaside",
    name: "Seaside Pier",
    locale: "PIER PAVILION, SANTA MONICA",
    stampLocale: "PIER PAVILION",
    motto: "SALT AIR FREE",
    tagline: "Salt air included at no extra charge.",
    place: "Santa Monica, California",
    prefix: "SEA",
    accent: "#2F6B5E",
    paper: "#F8F4E6",
    map: { x: 148, y: 168 },
    prompts: [
      "SQUINT INTO THE SUN",
      "HOLD AN INVISIBLE ICE CREAM",
      "WINDSWEPT HAIR — SELL IT",
      "SAILOR'S SALUTE",
      "A SEAGULL TOOK YOUR CHIPS",
      "POSTCARD SMILE",
      "LOOK OUT FOR LAND",
      "BEST CANNONBALL FACE",
    ],
  },
  {
    id: "niagara",
    name: "Niagara Falls",
    locale: "TABLE ROCK, ONTARIO",
    stampLocale: "NIAGARA FALLS, ONT.",
    motto: "HONEYMOON CAPITAL",
    tagline: "Issued only within sound of the falls.",
    place: "Niagara Falls, Ontario",
    prefix: "NIA",
    accent: "#37596E",
    paper: "#F4F1E6",
    map: { x: 281, y: 157 },
    exclusive: {
      place: "NIAGARA FALLS, ON",
      note: "Presence simulated for this demonstration.",
    },
    prompts: [
      "HOLD ONTO YOUR HAT",
      "POINT AT THE FALLS",
      "YOU FORGOT THE PONCHO",
      "HONEYMOON POSE",
      "BRACE AGAINST THE MIST",
      "AWE — REAL AWE",
      "BARREL RIDER'S SALUTE",
      "SHOUT OVER THE ROAR",
    ],
  },
];

export function getBooth(id: BoothId): Booth {
  return BOOTHS.find((b) => b.id === id) ?? BOOTHS[0];
}
