import type { Booth } from "./types";
import { CHARTERS } from "./charters";

export const BOOTHS: Booth[] = [
  {
    id: "standard",
    kind: "place",
    glyph: "camera",
    name: "The Standard",
    locale: "HEAD OFFICE, TORONTO",
    stampLocale: "HEAD OFFICE",
    motto: "HONEST LIGHT",
    tagline: "The company's original apparatus. Honest light, plain dealing.",
    place: "Toronto, Canada",
    prefix: "STD",
    accent: "#1F3A5F",
    paper: "#F9F4E9",
    map: { x: 238, y: 112 },
    mapTrue: { x: 259, y: 158 },
    prompts: [
      "SIT UP STRAIGHT, PLEASE",
      "NOW — A REAL SMILE",
      "LOOK AT YOUR COMPANION",
      "EYES CLOSED, CHIN UP",
      "A BIG LAUGH, GO",
      "PROFILE, PLEASE",
      "LEAN IN TOGETHER",
      "SERIOUS, LIKE A PASSPORT",
    ],
  },
  {
    id: "midnight",
    kind: "place",
    glyph: "moon",
    name: "Midnight Express",
    locale: "SLEEPER CAR No. 9",
    stampLocale: "SLEEPER CAR No. 9",
    motto: "LAST SERVICE 23:59",
    tagline: "Fitted to the night train. Last service 23:59.",
    place: "Aboard the night train",
    prefix: "MDX",
    accent: "#44406E",
    paper: "#F5F0E4",
    map: { x: 210, y: 134 },
    prompts: [
      "PRETEND YOU'RE BEING FOLLOWED",
      "WHISPER A SECRET",
      "LOOK OUT THE WINDOW",
      "TIP AN IMAGINARY HAT",
      "SLEEPY EYES",
      "TOAST WITH INVISIBLE GLASSES",
      "GAZE AT SOMETHING FAR AWAY",
      "CAUGHT MID-LAUGH",
    ],
  },
  {
    id: "seaside",
    kind: "place",
    glyph: "waves",
    name: "Seaside Pier",
    locale: "PIER PAVILION, SANTA MONICA",
    stampLocale: "PIER PAVILION",
    motto: "SALT AIR FREE",
    tagline: "Salt air included at no extra charge.",
    place: "Santa Monica, California",
    prefix: "SEA",
    accent: "#2F6B5E",
    paper: "#F8F4E6",
    map: { x: 140, y: 196 },
    prompts: [
      "SQUINT INTO THE SUN",
      "HOLD AN INVISIBLE ICE CREAM",
      "WINDSWEPT HAIR — SELL IT",
      "SAILOR'S SALUTE",
      "A SEAGULL TOOK YOUR CHIPS",
      "POSTCARD SMILE",
      "LOOK OUT FOR LAND",
      "BEST CANNONBALL FACE",
    ],
  },
  {
    id: "montreal",
    kind: "place",
    glyph: "fleur",
    name: "Vieux-Montréal",
    locale: "GARE WINDSOR, MONTRÉAL",
    stampLocale: "MONTRÉAL, QUÉ.",
    motto: "BONJOUR-HI",
    tagline: "Cobblestones, cathedral light, and a second language.",
    place: "Montréal, Québec",
    prefix: "MTL",
    accent: "#5A3F6E",
    paper: "#F6F1E6",
    map: { x: 293, y: 128 },
    mapTrue: { x: 273, y: 147 },
    prompts: [
      "SAY BONJOUR-HI",
      "INVISIBLE CROISSANT, BIG BITE",
      "WINTER COAT SHRUG",
      "GARGOYLE FACE",
      "LOOK UP AT THE SPIRES",
      "TOURIST WITH A MAP",
      "JAZZ HANDS, OBVIOUSLY",
      "POUTINE DAYDREAM",
    ],
  },
  {
    id: "niagara",
    kind: "place",
    glyph: "falls",
    name: "Niagara Falls",
    locale: "TABLE ROCK, ONTARIO",
    stampLocale: "NIAGARA FALLS, ONT.",
    motto: "HONEYMOON CAPITAL",
    tagline: "Issued only within sound of the falls.",
    place: "Niagara Falls, Ontario",
    prefix: "NIA",
    accent: "#37596E",
    paper: "#F4F1E6",
    map: { x: 268, y: 196 },
    mapTrue: { x: 260, y: 160 },
    exclusive: {
      place: "TABLE ROCK, NIAGARA FALLS",
      note: "Presence verified by location — or simulated for demonstration.",
      geo: { lat: 43.079, lng: -79.0788, radiusKm: 2.5 },
    },
    prompts: [
      "HOLD ONTO YOUR HAT",
      "POINT AT THE FALLS",
      "YOU FORGOT THE PONCHO",
      "HONEYMOON POSE",
      "BRACE AGAINST THE MIST",
      "AWE — REAL AWE",
      "BARREL RIDER'S SALUTE",
      "SHOUT OVER THE ROAR",
    ],
  },
  {
    id: "midsummer",
    kind: "seasonal",
    glyph: "bunting",
    name: "Midsummer Lawn",
    locale: "THE COMPANY GARDENS",
    stampLocale: "COMPANY GARDENS",
    motto: "DUSK AT NINE",
    tagline: "Set out on the lawn for the long evenings. June to August.",
    place: "Wherever summer finds you",
    prefix: "MSR",
    accent: "#6B7C3F",
    paper: "#F8F4E2",
    season: { months: [5, 6, 7], returns: "RETURNS IN JUNE" },
    prompts: [
      "GOLDEN HOUR SQUINT",
      "CHEERS WITH LEMONADE",
      "CAUGHT A FIREFLY",
      "LAWN CHAIR LEAN",
      "TIP YOUR SUNHAT",
      "BAREFOOT ON GRASS",
      "WATCH THE LONG DUSK",
      "PICNIC THIEF",
    ],
  },
  {
    id: "firstsnow",
    kind: "seasonal",
    glyph: "snow",
    name: "First Snow",
    locale: "THE WINTER PLATFORM",
    stampLocale: "WINTER PLATFORM",
    motto: "BUNDLE UP",
    tagline: "Wheeled out when the first flakes hold. December to February.",
    place: "Wherever winter finds you",
    prefix: "SNO",
    accent: "#3E5E78",
    paper: "#F4F2EA",
    season: { months: [11, 0, 1], returns: "RETURNS IN DECEMBER" },
    prompts: [
      "CATCH A SNOWFLAKE",
      "MITTENS UP",
      "SHIVER, DRAMATICALLY",
      "SNOWBALL WIND-UP",
      "FOG THE GLASS",
      "HOT CHOCOLATE HANDS",
      "FRESH POWDER GRIN",
      "SCARF OVER NOSE",
    ],
  },
];

export const PLACES = BOOTHS.filter((b) => b.kind === "place");
export const SEASONALS = BOOTHS.filter((b) => b.kind === "seasonal");

export function isInSeason(booth: Booth, date = new Date()): boolean {
  if (!booth.season) return true;
  return booth.season.months.includes(date.getMonth());
}

// Strict lookup — null when the id isn't a known booth/charter, unlike
// getBooth() below which always returns something displayable. Used where a
// wrong/typo'd id must be ignored rather than silently redirected to a
// fallback booth (e.g. the ?booth= deep-link param from a share page CTA).
export function findBooth(id: string): Booth | null {
  return BOOTHS.find((b) => b.id === id) ?? CHARTERS.find((b) => b.id === id) ?? null;
}

export function getBooth(id: string): Booth {
  return findBooth(id) ?? BOOTHS[0];
}
